export const liverPool_Players = [
  {
    id: 1,
    Name: "allana",
    fullName: "adam lallana",
    startMatch: false,
    DOB: "May 10, 1988",
    Age: "32",
    POB: "England St Albans",
    Citizenship: "England",
    Height: "1,72",
    Position: "Attacking Midfield",
    Agent: "Stellar Football Ltd",
    img: "img/adam-lallana.jpg",
  },

  {
    id: 2,
    Name: "Moreno",
    fullName: "Alberto Moreno",
    startMatch: false,
    DOB: "Jul 5, 1992",
    Age: "27",
    POB: "Spain Sevilla",
    Citizenship: "Spain",
    Height: "1,71",
    Position: "Left Back",
    Agent: "Stellar Football Ltd",
    img: "img/Alberto-Moreno.jpg",
  },

  {
    id: 3,
    Name: "Robertson",
    fullName: "Andy Robertson",
    startMatch: false,
    DOB: "March 11 1994",
    Age: "26",
    POB: "Scotland  Glasgow",
    Citizenship: "Scotland",
    Height: "1,78",
    Position: "Left Back",
    Agent: "Stellar Football Ltd",
    img: "img/Andy-Robertson.jpg",
  },

  {
    id: 4,
    Name: "Sturridge",
    fullName: "Daniel Sturridge",
    startMatch: false,
    DOB: " Sep 1, 1989",
    Age: "30",
    POB: "England  Birmingham",
    Citizenship: "England",
    Height: "1,85",
    Position: "Centre-Forward",
    Agent: "Stellar Football Ltd",
    img: "img/Daniel-Sturridge.jpg",
  },

  {
    id: 5,
    Name: "Firmino",
    fullName: "Roberto Firmino",
    startMatch: false,
    DOB: " Apr 18, 1995",
    Age: "25",
    POB: "Belgium  Ostend",
    Citizenship: "Belgium",
    Height: "1,85",
    Position: "Centre-Forward",
    Agent: "Stellar Football Ltd",
    img: "img/Divock-Origi.jpg",
  },

  {
    id: 6,
    Name: "Solanke",
    fullName: "Dominic Solanke",
    startMatch: false,
    DOB: " Sep 14, 1997",
    Age: "22",
    POB: "England  Reading",
    Citizenship: "England",
    Height: "1,87",
    Position: "Centre-Forward",
    Agent: "Stellar Football Ltd",
    img: "img/Dominic-Solanke.jpg",
  },

  {
    id: 7,
    Name: "Wijnaldum",
    fullName: "Gini Wijnaldum",
    startMatch: false,
    DOB: " Nov 11, 1990 ",
    Age: "29",
    POB: "Netherland   Rotterdam",
    Citizenship: "Netherland",
    Height: "1,75",
    Position: "Central Midfield",
    Agent: "Football Mix B.V.",
    img: "img/Gini-Wijnaldum.jpg",
  },

  {
    id: 8,
    Name: "Matip",
    fullName: "Joel Matip",
    startMatch: false,
    DOB: " Aug 8, 1991 ",
    Age: "28",
    POB: "Cameroon   Bochum",
    Citizenship: "Cameroon",
    Height: "1,95",
    Position: "Center Back",
    Agent: "ASBW Sport Marketing.",
    img: "img/Joel-Matip.jpg",
  },

  {
    id: 9,
    Name: "Salah",
    fullName: "Mohamed Salah",
    startMatch: false,
    DOB: " Jun 15, 1992 ",
    Age: "27",
    POB: "Egypt   Nagrig",
    Citizenship: "Egypt",
    Height: "1,75",
    Position: "Right Winger",
    Agent: "ASBW Sport Marketing.",
    img: "img/Mohamed-Salah.jpg",
  },

  {
    id: 10,
    Name: "Keita",
    fullName: "Naby Keita",
    startMatch: false,
    DOB: " Feb 10, 1995 ",
    Age: "25",
    POB: "Guinea   Conakry",
    Citizenship: "Guinea",
    Height: "1,72",
    Position: "Central Midfield",
    Agent: "arena11 sports group.",
    img: "img/Naby-Keita.jpg",
  },

  {
    id: 11,
    Name: "Phillips",
    fullName: "Nathaniel Phillips",
    startMatch: false,
    DOB: "Mar 21, 1997",
    Age: "23",
    POB: "England   Bolton",
    Citizenship: "England",
    Height: "1,90",
    Position: "Centre-Back",
    Agent: "arena11 sports group",
    img: "img/Nathaniel-Phillips.jpg",
  },

  {
    id: 12,
    Name: "Klavan",
    fullName: "Ragnar Klavan",
    startMatch: false,
    DOB: "Oct 30, 1985",
    Age: "34",
    POB: "Estonia   Viljandi",
    Citizenship: "Estonia",
    Height: "1,90",
    Position: "Centre-Back",
    Agent: "SFI",
    img: "img/Ragnar-Klavan.jpg",
  },

  {
    id: 13,
    Name: "Firmino",
    fullName: "Roberto Firmino",
    startMatch: false,
    DOB: "Oct 2, 1991",
    Age: "28",
    POB: "Brazil   Macei�, State of Alagoas",
    Citizenship: "Brazil",
    Height: "1,90",
    Position: "Centre-forward",
    Agent: "ROGON",
    img: "img/Roberto-Firmino.jpg",
  },
  {
    id: 14,
    Name: "Mane",
    fullName: "Sadio Mane",
    startMatch: false,
    DOB: "Apr 10, 1992",
    Age: "28",
    POB: "senegal   Sedhiou",
    Citizenship: "Senegal",
    Height: "1,75",
    Position: "Left Winger",
    Agent: "Sedhiou",
    img: "img/Sadio-Mane.jpg",
  },

  {
    id: 15,
    Name: "van Dijk",
    fullName: "Virgil van Dijk",
    startMatch: false,
    DOB: "Jul 8, 1991",
    Age: "28",
    POB: "Netherlands   Breda",
    Citizenship: "Netherlands",
    Height: "1,98",
    Position: "Centre-Back",
    Agent: "Sedhiou",
    img: "img/Virgil-van-Dijk.jpg",
  },

  {
    id: 16,
    Name: "Shaqiri",
    fullName: "Xherdan Shaqiri",
    startMatch: false,
    DOB: "Oct 10, 1991",
    Age: "28",
    POB: "Switzerland   Gjilan",
    Citizenship: "Switzerland",
    Height: "1,69",
    Position: "Right Winger",
    Agent: " ESHA",
    img: "img/Xherdan-Shaqiri.jpg",
  },
  {
    id: 17,
    Name: "Mignolet",
    fullName: "Simon Mignolet",
    startMatch: false,
    DOB: "Mar 6, 1988",
    Age: "32",
    POB: "Belgium   Sint-Truiden",
    Citizenship: "Belgium",
    Height: "1,93",
    Position: "Goalkeeper",
    Agent: " ESHA",
    img: "img/Simon-Mignolet.jpg",
  },
];

export const singlePerson = {
  id: 18,
  Name: "Klopp",
  fullName: "Jurgen Klopp",
  startMatch: false,
  DOB: "Jun 6, 1967",
  Age: "52",
  POB: "Germany   Stuttgart",
  Citizenship: "Germany",
  Height: "1,93",
  Position: "Coach",
  Agent: " ESHA",
  img: "img/Jurgen-Klopp.jpg",
};
